In [28]:
from tkinter import X
import numpy as np
import pandas as pd

from sklearn import datasets, linear_model
import matplotlib.pyplot as plt

data=pd.read_csv('Daily_Demand_Forecasting_Orders.csv')
data.head()

,WoM,NU-order,Urgent order,Order type A,Order type B,Order type C,FSO,OFTRCS,B(1),B(2),B(3),Target
1,4,316.307,223.270,61.543,175.586,302.448,0.000,65556,44914,188411,14793,539.577
1,5,128.633,96.042,38.058,56.037,130.580,0.000,40419,21399,89461,7679,224.675
1,6,43.651,84.375,21.826,25.125,82.461,1.386,11992,3452,21305,14947,129.412
2,2,171.297,127.667,41.542,113.294,162.284,18.156,49971,33703,69054,18423,317.120
2,3,90.532,113.526,37.679,56.618,116.220,6.459,48534,19646,16411,20257,210.517

In [26]:
#data.info()
#data.describe()
data.head()
#data.mode(1,2)
#data['o-rings'].value_counts().plot(kind='pie', autopct='%.2f', figsize=(7, 7), title= 'FSO')

,WoM,NU-order,Urgent order,Order type A,Order type B,Order type C,FSO,OFTRCS,B(1),B(2),B(3),Target
1,4,316.307,223.270,61.543,175.586,302.448,0.000,65556,44914,188411,14793,539.577
1,5,128.633,96.042,38.058,56.037,130.580,0.000,40419,21399,89461,7679,224.675
1,6,43.651,84.375,21.826,25.125,82.461,1.386,11992,3452,21305,14947,129.412
2,2,171.297,127.667,41.542,113.294,162.284,18.156,49971,33703,69054,18423,317.120
2,3,90.532,113.526,37.679,56.618,116.220,6.459,48534,19646,16411,20257,210.517

In [4]:
data.corr()

,WoM,NU-order,Urgent order,Order type A,Order type B,Order type C,FSO,OFTRCS,B(1),B(2),B(3),Target
WoM,1.000000,-0.416331,-0.517106,-0.068894,-0.376512,-0.448823,-0.132397,-0.339485,-0.051815,-0.577035,-0.012251,-0.435286
NU-order,-0.416331,1.000000,0.564796,0.561397,0.827186,0.752627,-0.057150,0.246937,0.732357,0.788192,0.132857,0.934518
Urgent order,-0.517106,0.564796,1.000000,0.412817,0.508929,0.767155,-0.011452,0.242268,0.230618,0.660868,0.031260,0.729785
Order type A,-0.068894,0.561397,0.412817,1.000000,0.438734,0.218651,0.064525,-0.151762,0.675328,0.294374,0.230369,0.559735
Order type B,-0.376512,0.827186,0.508929,0.438734,1.000000,0.523598,-0.122432,0.127111,0.592845,0.713674,0.067325,0.900673
Order type C,-0.448823,0.752627,0.767155,0.218651,0.523598,1.000000,0.007906,0.442404,0.330186,0.718739,0.031053,0.804984
FSO,-0.132397,-0.057150,-0.011452,0.064525,-0.122432,0.007906,1.000000,0.197670,0.003523,-0.055066,0.294567,-0.052116
OFTRCS,-0.339485,0.246937,0.242268,-0.151762,0.127111,0.442404,0.197670,1.000000,-0.162309,0.240450,0.231614,0.244712
B(1),-0.051815,0.732357,0.230618,0.675328,0.592845,0.330186,0.003523,-0.162309,1.000000,0.262905,0.221335,0.630365
B(2),-0.577035,0.788192,0.660868,0.294374,0.713674,0.718739,-0.055066,0.240450,0.262905,1.000000,-0.108797,0.798447
B(3),-0.012251,0.132857,0.031260,0.230369,0.067325,0.031053,0.294567,0.231614,0.221335,-0.108797,1.000000,0.100901
Target,-0.435286,0.934518,0.729785,0.559735,0.900673,0.804984,-0.052116,0.244712,0.630365,0.798447,0.100901,1.000000

In [27]:
X = data['NU-order'].values.reshape(-1,1)
X2 = data['Order type A'].values.reshape(-1,1) #colocada por mi
y = data['Target'].values.reshape(-1,1)

## preparar los datos de entrenamiento y prueba
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2)
## crear el objeto lr de tipo regresion lineal
lr=linear_model.LinearRegression()

## mostrar el resultado de la correlacion 
print(data.corr())

                   WoM  NU-order  Urgent order  Order type A  Order type B  \
WoM           1.000000 -0.416331     -0.517106     -0.068894     -0.376512
NU-order     -0.416331  1.000000      0.564796      0.561397      0.827186
Urgent order -0.517106  0.564796      1.000000      0.412817      0.508929
Order type A -0.068894  0.561397      0.412817      1.000000      0.438734
Order type B -0.376512  0.827186      0.508929      0.438734      1.000000
Order type C -0.448823  0.752627      0.767155      0.218651      0.523598
FSO          -0.132397 -0.057150     -0.011452      0.064525     -0.122432
OFTRCS       -0.339485  0.246937      0.242268     -0.151762      0.127111
B(1)         -0.051815  0.732357      0.230618      0.675328      0.592845
B(2)         -0.577035  0.788192      0.660868      0.294374      0.713674
B(3)         -0.012251  0.132857      0.031260      0.230369      0.067325
Target       -0.435286  0.934518      0.729785      0.559735      0.900673

              Order type C       FSO    OFTRCS      B(1)      B(2)      B(3)  \
WoM              -0.448823 -0.132397 -0.339485 -0.051815 -0.577035 -0.012251
NU-order          0.752627 -0.057150  0.246937  0.732357  0.788192  0.132857
Urgent order      0.767155 -0.011452  0.242268  0.230618  0.660868  0.031260
Order type A      0.218651  0.064525 -0.151762  0.675328  0.294374  0.230369
Order type B      0.523598 -0.122432  0.127111  0.592845  0.713674  0.067325
Order type C      1.000000  0.007906  0.442404  0.330186  0.718739  0.031053
FSO               0.007906  1.000000  0.197670  0.003523 -0.055066  0.294567
OFTRCS            0.442404  0.197670  1.000000 -0.162309  0.240450  0.231614
B(1)              0.330186  0.003523 -0.162309  1.000000  0.262905  0.221335
B(2)              0.718739 -0.055066  0.240450  0.262905  1.000000 -0.108797
B(3)              0.031053  0.294567  0.231614  0.221335 -0.108797  1.000000
Target            0.804984 -0.052116  0.244712  0.630365  0.798447  0.100901

                Target
WoM          -0.435286
NU-order      0.934518
Urgent order  0.729785
Order type A  0.559735
Order type B  0.900673
Order type C  0.804984
FSO          -0.052116
OFTRCS        0.244712
B(1)          0.630365
B(2)          0.798447
B(3)          0.100901
Target        1.000000

In [6]:
#entrenar X_train y y_train
lr.fit(X_train ,y_train)
y_predict=lr.predict(X_test)

valor_b=lr.coef_
valor_a=lr.intercept_
print("el valor de la pendiente es "+str(lr.coef_))
print("el valor de la b es "+str(lr.intercept_))

el valor de la pendiente es [[1.16412921]]
el valor de la b es [95.03796108]

In [14]:
# vector a graficar
yy=valor_a+(valor_b*X)
# comando para graficar
#plt.scatter(X, y,  color='gray')
#plt.title("Resultados")
#plt.plot(X,yy)
#plt.show()

In [12]:
valor_predecir = lr.predict([[7]])
print(int(valor_predecir))
##puntuacion
print(lr.score(X_train, y_train))

103
0.8957764327042695